import type { Project, Task, InboxMessage, Integration } from './types';

export const mockProjects: Project[] = [
  {
    id: "SENNA-TOWER-01",
    name: "Senna Tower - estudo de viabilidade",
    color: "#004d6d",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    contracted_value: 184100,
    tasks_total: 521030,
    folder: "Senna Tower",
    client: "FG | Talls Solution",
    area: "Certificação LEED",
    created_at: "2025-01-10T12:00:00Z",
    owner: "Eduardo Yamada",
    label_code: "ST28677-25",
    flow_date: "23/03/26",
    contract_original_value: 184100,
    contract_aditivo_value: 0,
    navis_launched_value: 605100,
    reajuste_adicional_value: 0,
    margin_pct: 2,
    total_planned_value: 521030,
    billing_day: 20,
    approved_by_owner: false,
    is_critical: true,
    billing_profile: {
      id: "BP-01",
      projectId: "SENNA-TOWER-01",
      measurementDates: "Dia 20 de cada mês",
      billingDates: "D+5 após aprovação da medição",
      docsRequired: "Nota Fiscal, Relatório de Medição Wrike, CND, ART do projeto",
      isNewClient: false,
      notes: "Cliente exige envio em PDF único por e-mail administrativo."
    },
    contract_details: {
      id: "CON-01",
      projectId: "SENNA-TOWER-01",
      documentUrl: "https://sharepoint.cte.com.br/contratos/fg_talls_st28677.pdf",
      renewalDate: "2026-06-30",
      index: "INCC-M",
      expectedReturnDate: "2026-06-01",
      lastFupDate: "2026-05-24",
      status: "pending_client",
      originalValue: 184100,
      readjustedValue: 191464,
      reajustePct: 4.2,
    }
  },
  {
    id: "IEAAFWTFI4K6LZSU",
    name: "05-Comissionamento Corporate",
    color: "#007a83",
    responsible: "Camila Peixinho",
    email: "cmendonca@cte.com.br",
    contracted_value: 18000,
    tasks_total: 18000,
    folder: "05-Comissionamento",
    client: "Cyrela Commercial Properties",
    area: "Comissionamento",
    created_at: "2019-06-25T13:26:27Z",
    owner: "Camila Peixinho",
    label_code: "CP20442-19",
    flow_date: "20/05/26",
    contract_original_value: 18000,
    contract_aditivo_value: 0,
    navis_launched_value: 18000,
    reajuste_adicional_value: 0,
    margin_pct: 12,
    total_planned_value: 18000,
    billing_day: 25,
    approved_by_owner: true,
    is_critical: false,
    billing_profile: null,
    contract_details: null
  }
];

export const mockTasks: Task[] = [
  // Senna Tower - estudo de viabilidade tasks
  {
    id: "ST-T-01",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] WPO-08 Workshop Pré-obra - Parte 1 - Virtual",
    description: "Workshop de alinhamento com a equipe de obras e projetistas",
    value: 4500,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-06-23T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Obras",
    navis_num: "05",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-02",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] OPR-08-Owner Project Requirements",
    description: "Definição de requisitos do cliente corporativo",
    value: 3000,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-06-30T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Sistemas Prediais",
    navis_num: "08",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-03",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] RAP-01-Relatório de Análise de Projetos 1",
    description: "Primeiro relatório técnico das disciplinas de Engenharia",
    value: 10700,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-06-30T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Reajuste",
    navis_num: "Re",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-04",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] COI-05-Visita Técnica LEED Obra (01/60)",
    description: "Visita de inspeção da obra física para certificação",
    value: 5000,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-07-21T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Obras",
    navis_num: "05",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-05",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] RAP-01-Relatório de Análise de Projetos 2",
    description: "Análise complementar de projetos de ar condicionado",
    value: 10700,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-07-31T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Projeto",
    navis_num: "01",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-06",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] BOD-08-Basis of Design",
    description: "Estruturação das premissas de projeto sustentável",
    value: 9000,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-08-29T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Sistemas Prediais",
    navis_num: "08",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-07",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] PLC-08 Plano de Cx",
    description: "Plano geral de comissionamento de sistemas prediais",
    value: 4500,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-08-29T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Sistemas Prediais",
    navis_num: "08",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-08",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] RAP-01-Relatório de Análise de Projetos 3",
    description: "Terceiro relatório da equipe de certificação",
    value: 10700,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-09-30T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Projeto",
    navis_num: "01",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-09",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] VD-02-Coleta de Dados SM1",
    description: "Coleta e tabulação de dados ambientais in loco",
    value: 6000,
    status: "vis",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-09-30T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Eficiência",
    navis_num: "02",
    status_nf: "Concluído",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-10",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] PLA-03 Planilha de Validação de Dados Inicial",
    description: "Planilha consolidada de metas energéticas",
    value: 15000,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-09-30T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Projeto",
    navis_num: "la",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-11",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] RAP-01-Relatório de Análise de Projetos 4",
    description: "Revisão arquitetônica preliminar",
    value: 10700,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-09-30T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Projeto",
    navis_num: "01",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-12",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] COI-05-Visita Técnica LEED Obra (02/60)",
    description: "Vistoria física bimestral de sustentabilidade",
    value: 35000,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-10-06T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Obras",
    navis_num: "05",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-13",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] REL-03 Relatório ACV Inicial (emissão)",
    description: "Análise de Ciclo de Vida inicial",
    value: 27100,
    status: "apr",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2025-10-17T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Reajuste",
    navis_num: "el",
    status_nf: "Pago",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-14",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] COI-05-Visita Técnica LEED Obra (03/60)",
    description: "Vistoria física de auditoria",
    value: 5000,
    status: "vis",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2026-04-30T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Obras",
    navis_num: "05",
    status_nf: "Nota Enviada",
    pagamento: "Nota Atrasada",
    date_previous: "2026-03-30",
    value_previous: 5000,
    gap_justification: "Atraso na liberação da obra pelo cliente",
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-15",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] RAP-01-Relatório de Análise de Projetos 10",
    description: "Décimo relatório consolidado de engenharia",
    value: 10700,
    status: "fat",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2026-03-27T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Projeto",
    navis_num: "01",
    status_nf: "Enviar Nota",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  },
  {
    id: "ST-T-16",
    project_id: "SENNA-TOWER-01",
    name: "[ST28677-25-SEN] RAC-08 Relatório Análise de Compras (01/10)",
    description: "Verificação de fornecedores homologados",
    value: 3200,
    status: "vis",
    responsible: "Eduardo Yamada",
    email: "eduardoyamada@cte.com.br",
    due_date: "2032-11-01T17:00:00",
    created_at: "2025-06-10T12:00:00Z",
    etapa: "Sistemas Prediais",
    navis_num: "08",
    status_nf: "—",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Não Lançar"
  },

  // Other tasks
  {
    id: "IEAAFWTFKQLYEXV7",
    project_id: "IEAAFWTFI4K6LZSU",
    name: "[AC312U-19-XPI] VCX-08-Visita de campo de comissionamento 05",
    description: "[AC312U-19-XPI] VCX-08-Visita de campo de comissionamento 05",
    value: 18000,
    status: "fat",
    responsible: "Camila Peixinho",
    email: "cmendonca@cte.com.br",
    due_date: "2026-05-06T17:00:00",
    created_at: "2019-09-05T14:04:13Z",
    etapa: "Projeto",
    navis_num: "05",
    status_nf: "Enviar Nota",
    pagamento: "—",
    date_previous: null,
    value_previous: null,
    gap_justification: null,
    launch_navis: "Lançar"
  }
];

export const mockInboxMessages: InboxMessage[] = [
  {
    id: "MSG-01",
    title: "Fluxo de Caixa Pendente",
    body: "O fluxo de caixa de Senna Tower está pendente de aprovação do Líder Eduardo Yamada.",
    type: "approval",
    read: false,
    project_id: "SENNA-TOWER-01",
    task_id: null,
    created_at: "2026-05-25T10:00:00Z"
  }
];

export const mockIntegrations: Integration[] = [
  {
    id: "INT-01",
    name: "Conexão Wrike Real-Time",
    type: "wrike",
    status: "active",
    url: "https://api.wrike.com/v4",
    last_sync: "2026-05-26T09:00:00Z",
    created_at: "2025-01-01T00:00:00Z"
  }
];